title: Jason Symons
subtitle: Impact Monitoring Data Consultant
email: jason@jason-symons.com
description: Impact & Data Specialist
baseurl: ''
url: 'https://jason-symons.com'
domain: jason-symons.com
logo: /assets/img/logo.png
linkedin: jason-symons-monitoring
google_analytics: G-LSYGSLNBLY
github:
  is_user_page: false
  is_project_page: false
links:
  - label: jason@jason-symons.com
    icon: fas fa-fw fa-envelope-square
    url: 'mailto:jason@jason-symons.com'
  - label: jason-symons-monitoring
    icon: fa-brands fa-linkedin-in
    url: 'https://www.linkedin.com/in/jason-symons-monitoring/'
  - label: JSym
    icon: fa-brands fa-github
    url: 'https://github.com/JSym'
  - label: Resume
    icon: far fa-fw fa-file-pdf
    url: /assets/files/JASON_SYMONS - Resume - February 2025.pdf
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
  - jekyll-admin
safe: true
whitelist:
  - jekyll-admin
show_drafts: true
jekyll_admin:
  homepage: configuration
