# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jason Symons
subtitle:  Impact Monitoring Data Consultant
email: jason@jason-symons.com
description: Impact & Data Specialist

baseurl: "" # the subpath of your site, e.g. /blog
url: https://jason-symons.com # the base hostname & protocol for your site, e.g. http://example.com
domain: jason-symons.com
logo: /assets/img/logo.png
email: jason@jason-symons.com
linkedin: jason-symons-monitoring
google_analytics: G-LSYGSLNBLY
github:
  is_user_page: False
  is_project_page: False

links:
  - label: "jason@jason-symons.com"
    icon: "fas fa-fw fa-envelope-square"
    url: "mailto:jason@jason-symons.com"
  - label: "jason-symons-monitoring"
    icon: "fa-brands fa-linkedin-in"
    url: "https://www.linkedin.com/in/jason-symons-monitoring/"
  - label: "JSym"
    icon: "fa-brands fa-github"
    url: "https://github.com/JSym"
  - label: "+30 698 693 7851"
    icon: "fa-solid fa-phone-volume"
    url: "tel:00306986937851"
  - label: "Resume"
    icon: "far fa-fw fa-file-pdf"
    url: "/assets/files/JASON_SYMONS - Resume - February 2025.pdf"

#twitter_username: dontusetwitter
#github_username:  jekyll

# Build settings
#theme: minima
theme: jekyll-theme-minimal
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
 # - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
